name: Procesar Quiniela y Quinigol

on:
  workflow_dispatch:
    inputs:
      apuestas_json:
        description: "Objeto de apuestas en JSON"
        required: true
      partidos_json:
        description: "Objeto de los partidos en JSON"
        required: true

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Guardar apuestas y partidos
        run: |
          echo '${{ inputs.apuestas_json }}' > html/apuestas.json
          echo '${{ inputs.partidos_json }}' > html/partidos.json

      - name: Subir archivos a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: html

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v4