name: CI Release Version

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: CodeForgeGuild/ci-actions/.github/workflows/release.yml@v0
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
