name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE }}
      # Solo si se creó un nuevo release
      - name: Zip src/ folder
        if: steps.release.outputs.release_created == 'true'
        run: zip -r src.zip src/

      - name: Upload src.zip to GitHub Release
        if: steps.release.outputs.release_created == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: src.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
